### ISSUE TITLE
Trzeba naprawić/dodać placeholdery z placeholderAPI

### ISSUE THREAD

**Issue by vCren** [EternalCodeTeam/ChatFormatter#2]
Trzeba dodać placeholdery do formatu. Aby wszędzie działały. Przy próbie umieszczenia placeholdera wyskakuje błąd. I dlatego teraz nie wiem czy to jest błąd czy nie jest to dodane :/

`[00:05:34] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatFormatter v1.0.1
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.12.2.jar:git-Paper-1620]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1407) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1322) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.UnknownFormatConversionException: Conversion = 'p'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2855) ~[?:?]
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2891) ~[?:?]
	at java.util.Formatter.parse(Formatter.java:2747) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2671) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
	at java.lang.String.format(String.java:4143) ~[?:?]
	at com.eternalcode.formatter.ChatController.onChat(ChatController.java:73) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.12.2.jar:git-Paper-1620]
	... 11 more`

**Comment by Rollczi** [comment]
pokaż konfigurację

**Comment by vCren** [comment]
Przepraszam że tak długo, ale wyjechałem. Oto moja konfiguracja `#    ____ _           _   _____      ChatFormatter       _   _            
#   / ___| |__   __ _| |_|  ___|__  _ __ _ __ ___   __ _| |_| |_ ___ _ __ 
#  | |   | '_ \ / _` | __| |_ / _ \| '__| '_ ` _ \ / _` | __| __/ _ \ '__|
#  | |___| | | | (_| | |_|  _| (_) | |  | | | | | | (_| | |_| ||  __/ |   
#   \____|_| |_|\__,_|\__|_|  \___/|_|  |_| |_| |_|\__,_|\__|\__\___|_|   

# Do you want to use pre chat format? (Other plugins could join custom prefixes etc.)
# INFO: This option requires to use custom badges like {displayname} and {message} in each message.
preFormatting: false
defaultFormat: "{displayname} {arrow_right} {message}"

# Chat format for ranks (Vault) Support mini-messages and legacy colors

# We're recommending to use webui for mini-messages: https://webui.adventure.kyori.net/

# documentation is here: https://docs.adventure.kyori.net/minimessage/format.html
# Example usages:
# 
# Hover message:
# One line: <hover:show_text:'<red>test'>TEST
# Multiple lines: <hover:show_text:'<red>test'>Test<newline>Test2</hover>
# 
# Click message:
# Open URL: <click:open_url:'https://webui.adventure.kyori.net'>TEST</click>
# Run command: <click:run_command:/say hello>Click</click> to say hello
# Suggest command: <click:suggest_command:'/msg {displayname}'></click>
# 
# RGB and gradient message usage: 
# <color:#ff00ee>Example message</color>
# <gradient:#ff00ee:#f79459>Example message</gradient>

format:
  default: "{member} &f{displayname} &8{arrow_right} {message} "
  admin: "$template({admin}, &c)"

# It is used to shorten the text even more and keep the clean file!
templates:
  - "$template($rank, $color) -> '$rank $color{displayname} {test} %player_name% &8{arrow_right} $color{message}'"

# Placeholders, it allows you to make a shorter text, you can use some prefixes, characters etc. 
placeholders:
  {displayname}: "%1$s"
  {message}: "%2$s"
  {test}: "<hover:show_text:'<red>test'>TEST</hover>"
  {prefix}: "<b><gradient:#29fbff:#38b3ff>ChatFormatter</gradient></b>"
  {member}: "<b><color:#6e6764>Member</color></b>"
  {admin}: "[lang]test[/lang]<b><color:#ff4400>Admin</color></b>"
  {arrow_right}: "»"
  {arrow_left}: "«"`
  
  Czyli tak na prawdę w hoverze nie jest to obsługiwane... A tak normalnie w formacie chatu jest. I wydaje mi się że trzeba będzie ogarnąć tez placeholdery relatywne, chyba że papi ma to już w sobie np %rel....%

**Comment by vLuckyyy** [comment]
Rozwiązano 😄
