### ISSUE TITLE
[Compatability Issue] AsyncChatEvent is Not Updated

### ISSUE THREAD

**Issue by Peashooter101** [EternalCodeTeam/ChatFormatter#54]
Paper has updated on December 24, 2022 with a new update regarding AsyncChatEvent which includes a SignedMessage parameter in the AsyncChatEvent Constructor.

Currently the plugin does not support this change and will not work, see [GitHub: Paper AsyncChatEvent Commit](https://github.com/PaperMC/Paper/commit/c59922d94e91fb9820a52408c04038db56c6331b)

<details>
<summary>Stacktrace Error</summary>

```
[18:57:57 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatFormatter v1.0.4
java.lang.NoSuchMethodError: 'void io.papermc.paper.event.player.AsyncChatEvent.<init>(boolean, org.bukkit.entity.Player, java.util.Set, io.papermc.paper.chat.ChatRenderer, net.kyori.adventure.text.Component, net.kyori.adventure.text.Component)'
        at com.eternalcode.formatter.paper.ChatPaperPreparatory.prepare(ChatPaperPreparatory.java:31) ~[ChatFormatter-PaperSupport.v1.0.4.jar:?]
        at com.eternalcode.formatter.preparatory.ChatPreparatoryService.prepare(ChatPreparatoryService.java:24) ~[ChatFormatter.v1.0.4.jar:?]
        at com.eternalcode.formatter.ChatController.onChat(ChatController.java:117) ~[ChatFormatter.v1.0.4.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1879]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:413) ~[purpur-1.19.3.jar:git-Purpur-1879]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:99) ~[purpur-1.19.3.jar:git-Purpur-1879]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2483) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2639) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$18(ServerGamePacketListenerImpl.java:2319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
</details>

**Comment by vLuckyyy** [comment]
Hi, We will try to release a new version as soon as possible to fix this problem. Thank you very much for reporting this bug and happy new year!

**Comment by Rollczi** [comment]
I will use DI to inject parameters of a chat event constructor to support all versions.
